{"asctime": "2025-03-27 11:36:25,717", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:36:34,024", "name": "manage", "levelname": "ERROR", "message": "创建管理员用户失败: (pymysql.err.OperationalError) (1054, \"Unknown column 'full_name' in 'field list'\")\n[SQL: INSERT INTO users (username, email, hashed_password, full_name, is_active, is_superuser, last_login, updated_at) VALUES (%(username)s, %(email)s, %(hashed_password)s, %(full_name)s, %(is_active)s, %(is_superuser)s, %(last_login)s, %(updated_at)s)]\n[parameters: {'username': 'admin', 'email': 'admin@example.com', 'hashed_password': '$2b$12$am4MeMq./i2W52gnZn0mxeTAvJkyHp7naRB/4oSTcYTmHhxqs4Txq', 'full_name': '系统管理员', 'is_active': 1, 'is_superuser': 1, 'last_login': None, 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", "taskName": null}
{"asctime": "2025-03-27 11:37:40,181", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:37:49,269", "name": "manage", "levelname": "ERROR", "message": "创建管理员用户失败: (pymysql.err.ProgrammingError) (1146, \"Table 'admin_service.roles' doesn't exist\")\n[SQL: INSERT INTO roles (name, description, updated_at) VALUES (%(name)s, %(description)s, %(updated_at)s)]\n[parameters: {'name': '超级管理员', 'description': '系统超级管理员，拥有所有权限', 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "taskName": null}
{"asctime": "2025-03-27 11:38:50,808", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:39:07,428", "name": "manage", "levelname": "ERROR", "message": "创建管理员用户失败: (pymysql.err.ProgrammingError) (1146, \"Table 'admin_service.roles' doesn't exist\")\n[SQL: INSERT INTO roles (name, description, created_at, updated_at) VALUES (%(name)s, %(description)s, %(created_at)s, %(updated_at)s)]\n[parameters: {'name': '超级管理员', 'description': '系统超级管理员，拥有所有权限', 'created_at': datetime.datetime(2025, 3, 27, 3, 39, 7, 424509), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "taskName": null}
{"asctime": "2025-03-27 11:39:49,430", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:40:07,482", "name": "manage", "levelname": "ERROR", "message": "创建管理员用户失败: (pymysql.err.ProgrammingError) (1146, \"Table 'admin_service.roles' doesn't exist\")\n[SQL: INSERT INTO roles (name, description, created_at, updated_at) VALUES (%(name)s, %(description)s, %(created_at)s, %(updated_at)s)]\n[parameters: {'name': '超级管理员', 'description': '系统超级管理员，拥有所有权限', 'created_at': datetime.datetime(2025, 3, 27, 3, 40, 7, 478044), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "taskName": null}
{"asctime": "2025-03-27 11:40:46,874", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:41:04,947", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 11:47:51,483", "name": "manage", "levelname": "INFO", "message": "数据库初始化成功", "taskName": null}
{"asctime": "2025-03-27 12:25:38,465", "name": "manage", "levelname": "ERROR", "message": "启动服务失败: cannot find context for 'fork'", "taskName": null}
{"asctime": "2025-03-27 13:48:44,801", "name": "manage", "levelname": "ERROR", "message": "启动服务失败: cannot find context for 'fork'", "taskName": null}
